// 
//     MINOTAUR -- It's only 1/2 bull
// 
//     (C)opyright 2009 - 2013 The MINOTAUR Team
// 

//
// This file contains the documentation that will appear on the main page
// (index.html) generated by doxygen.
//

// /**
// @mainpage 
// \image html small.jpg
// \authors
// Team Minotaur at Argonne National Lab and UW-Madison 
// \authors
// Copyright 2009 - 2013
//
// <b> Additional Links </b>
// - <a href="http://mcs.anl.gov/minotaur">Minotaur Homepage</a>
// */

// Local Variables:
// mode: c++
// eval: (c-set-style "gnu")
// eval: (setq indent-tabs-mode nil)
// End:
